import "./globals.css";

export const metadata = {
  title: "Dua & Ruqyah",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <html lang="en">{children}</html>;
}
